library(lubridate)
completedata<-read.table("household_power_consumption.txt",sep = ";",header = TRUE,dec = ".",stringsAsFactors=FALSE,na = "?")
data <- completedata[completedata$Date %in% c("1/2/2007","2/2/2007") ,]
data$Sub_metering_1<-as.numeric(data$Sub_metering_1)
data$Sub_metering_2<-as.numeric(data$Sub_metering_2)
data$Sub_metering_3<-as.numeric(data$Sub_metering_3)
data$Global_active_power<-as.numeric(data$Global_active_power)
data$Global_reactive_power<-as.numeric(data$Global_reactive_power)
data$Voltage<-as.numeric(data$Voltage)
data$Date<-dmy(data$Date)
data$datetime<-strptime(paste(data$Date, data$Time),"%Y-%m-%d %H:%M:%S")
png("plot4.png",width = 480 , height = 480,units = "px")
par(mfrow = c(2, 2))
plot(data$datetime,data$Global_active_power,ylab = "Global Active Power(kilowatts)",xlab = "",main="",type = "l")
plot(data$datetime,data$Voltage,ylab = "Voltage",xlab = "datetime",main="",type = "l")
plot(data$datetime,data$Sub_metering_1,ylab = "Energy sub metering",main="",xlab="",type = "l")
lines(data$datetime,data$Sub_metering_2,col ="red",type = "l")
lines(data$datetime,data$Sub_metering_3,col ="blue",type = "l")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=1, col=c("black", "red", "blue"))
plot(data$datetime,data$Global_reactive_power,ylab = "Global_reactive_power",main="",type = "l",xlab = "datetime")
dev.off()